/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { CLIENTID, SendGameInviteSignal } from "../../Connections/socket";

export default function Model({ ...props }) {
	const group = useRef();
	const { nodes, materials } = useGLTF("/ExtendedArena.gltf");

	return (
		<group ref={group} {...props} dispose={null}>
			{props.children}
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Floor.geometry}
				material={materials.floor}
				position={[0.9, 0.65, -2.16]}
				scale={[23.84, 0.66, 22.92]}
			/>
			<mesh onClick={() => {
				console.log('Stage Clicked')
			}}
				castShadow
				receiveShadow
				geometry={nodes.Stage.geometry}
				material={materials.StageMaterial}
				position={[0, 2.1, -7.44]}
				scale={[8.79, 0.89, 4.54]}
			/>
			<group onClick={() => {
				console.log('Dice board clicked');
				props.setDiceBoardShow(true);
				props.gameLoaded.current = 'dice';
			}} position={[12.46, 2.89, 5.95]} scale={1.64}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube002.geometry}
					material={materials.wood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube002_1.geometry}
					material={materials.dice}
				/>
			</group>
			<group onClick={() => {
				SendGameInviteSignal(props.worldID, 'chess');
				props.setChessBoardShow(true);
				props.gameLoaded.current = 'chess';
				console.log('Chess Board Clicked');
			}} position={[-11.84, 3.04, 6.05]} scale={1.64}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube003.geometry}
					material={materials["wood.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube003_1.geometry}
					material={materials["chess.001"]}
				/>
			</group>
			<group position={[0, 10, 0]} scale={[15, 10, 15]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001.geometry}
					material={materials.ceiling}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001_1.geometry}
					material={materials.walls}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/ExtendedArena.gltf");